server:
  port: ${PORT:8081}

spring:
  sql:
    init:
      mode: always

  application:
    name: Nomad Rates Sentinel

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6tvpthaae7s73e6uu60-a:5432/nomad_rates?connectTimeout=3&socketTimeout=10&tcpKeepAlive=true}
    username: ${SPRING_DATASOURCE_USERNAME:nomad_rates_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ycYCPEpHCFKaQd1GJ4hJXl0j7eOmcfOl}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
      validation-timeout: 2000
      initialization-fail-timeout: 5000

  threads:
    virtual:
      enabled: true

rates:
  adapters:
    request-timeout-ms: 30000
    nbk:
      url: https://nationalbank.kz/en/exchangerates/ezhednevnye-oficialnye-rynochnye-kursy-valyut
    xe:
      url: https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=KZT
  cache:
    sync-ttl: ${RATES_CACHE_SYNC_TTL:30s}
