spring:
  config:
    activate:
      on-profile: reactive

  main:
    web-application-type: reactive

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://dpg-d6tvpthaae7s73e6uu60-a:5432/nomad_rates?connectTimeout=PT3S&tcpKeepAlive=true}
    username: ${SPRING_R2DBC_USERNAME:nomad_rates_user}
    password: ${SPRING_R2DBC_PASSWORD:ycYCPEpHCFKaQd1GJ4hJXl0j7eOmcfOl}
