spring:
  config:
    activate:
      on-profile: reactive

  main:
    web-application-type: reactive

  r2dbc:
    url: postgresql://nomad_rates_user:ycYCPEpHCFKaQd1GJ4hJXl0j7eOmcfOl@dpg-d6tvpthaae7s73e6uu60-a/nomad_rates
    username: nomad_rates_user
    password: ycYCPEpHCFKaQd1GJ4hJXl0j7eOmcfOl
